parent(ram,sita).
parent(ram,shyam).
parent(siya,sita).
parent(siya,shyam).
parent(sita,theo).
parent(kabir,theo).
parent(shyam,gita).
parent(shyam,rahul).
parent(roshni,gita).
parent(roshni,rahul).
male(ram).
male(kabir).
male(shyam).
male(theo).
male(rahul).
female(siya).
female(sita).
female(roshni).
female(gita).
grandparent(X,Z):-parent(X,Y),parent(Y,Z).
grandfather(X,Z):-male(X),parent(X,Y),parent(Y,Z).
grandmother(X,Z):-female(X),parent(X,Y),parent(Y,Z).
husband(X,Y):-male(X),parent(Y,Z),parent(X,Z).
wife(X,Y):-female(X),parent(Y,Z),parent(X,Z).
son(X,Y):-male(X),parent(Y,X).
daughter(X,Y):-female(X),parent(Y,X).
mother(X,Y):-female(X),parent(X,Y).
father(X,Y):-male(X),parent(X,Y).
sibling(X,Y):-parent(Z,X),parent(Z,Y).
brother(X,Y):-male(X),parent(Z,X),parent(Z,Y).
sister(X,Y):-female(X),parent(Z,X),parent(Z,Y).
uncle(X,Y):-male(X),parent(Z,Y),sibling(X,Z).
aunt(X,Y):-female(X),parent(Z,Y),sibling(X,Z).
soninlaw(X,Y):-male(X),husband(X,Z),parent(Y,Z).
daughterinlaw(X,Y):-female(X),wife(X,Z),parent(Y,Z).

